title: "Naman's Digital Home"
author: "Naman Aggarwal"
description: "Hola Builders"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "blog.html", title: Home}
  - {file: "/blog.md", title: Blog}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:namanagg1930@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/nerdynaman"}
  - {title: Twitter, icon: twitter, url: "https://www.x.com/nerdynaman"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-toc
